config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :trains
  resources :stations
  resources :train_stations

  get 'search_result' => 'home#search_result'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/station.rb
class Station < ApplicationRecord
  has_many :train_stations
  has_many :trains, through: :train_stations
  validates :name, :code, :state, :longitude, :latitude, presence: true
  validates :name, :code, uniqueness: true  
  validates :longitude, :latitude, numericality: true
end

app/models/train.rb
class Train < ApplicationRecord
  has_many :train_stations
  has_many :stations, through: :train_stations
  paginates_per 10
  validates :name, :source_station, :last_station, :start_time, :end_time, presence: true
  validates :name, uniqueness: true
  validate :valid_time_range

  def valid_time_range
    return unless end_time? && start_time?
    # return unless end_time.present? && start_time.present?

    unless end_time.after?(start_time)
      errors.add(:start_time, "can not be greater than end time")
    end
  end

  def train_hours
    "#{((end_time.to_time - start_time.to_time)/1.hours).abs.round(2)} hours"
  end

  def train_duration
    "#{end_time.strftime("%H:%M %p")} to #{start_time.strftime("%H:%M %p")} (#{train_hours})"
  end
end

app/models/train_station.rb
class TrainStation < ApplicationRecord
  belongs_to :train
  belongs_to :station
  validates :day, :distance_in_km, :arrival_time, :departure_time, :total_halt_in_minutes, :station_id, :train_id, presence: true
  validates :distance_in_km, numericality: { only_integer: true }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :set_train_search

  def index; end

  def search_result; end

  private

  def set_train_search
    @q = Train.ransack(params[:q])
    @trains = @q.result(distinct: true)
  end
end

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: %i[show edit update destroy]

  def index
    @stations = Station.all
  end

  def new
    @station = Station.new
  end

  def create
    @station = Station.new(station_params)
    if @station.save
      redirect_to stations_path, notice: 'Station has been added'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @station.update(station_params)
      redirect_to stations_path(@station)
    else
      render :edit
    end
  end

  def destroy
    @station.destroy
    redirect_to stations_path
  end

  private

  def station_params
    params.require(:station).permit(:code, :name, :state, :longitude, :latitude)
  end

  def set_station
    @station = Station.find(params[:id])
  end

end

app/controllers/train_stations_controller.rb
class TrainStationsController < ApplicationController
  before_action :set_train_station, only: %i[show edit update destroy]
  
  def index
    @train_stations = TrainStation.all
  end

  def new
    @train_station = TrainStation.new
  end

  def create
    @train_station = TrainStation.new(train_station_params)
    if @train_station.save
      redirect_to train_stations_path, notice: 'Attributes has been added'
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @train_station.update(train_station_params)
      redirect_to train_stations_path
    else
      render :edit
    end
  end


  def destroy
    @train_station.destroy
    redirect_to train_stations_path
  end

  private

  def train_station_params
    params.require(:train_station).permit(:train_id, :station_id, :day, :distance_in_km, :arrival_time, :departure_time, :total_halt_in_minutes)
  end

  def set_train_station
    @train_station = TrainStation.find(params[:id])
  end

end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: %i[show edit update destroy]
  
  def index
    @q = Train.ransack(params[:q])
    @trains = @q.result(distinct: true).page(params[:page])
  end


  def new
    @train = Train.new
  end

  def create
    @train = Train.new(train_params)
    if @train.save
      redirect_to trains_path, notice: 'Train has been added'
    else
      render :new
    end
  end


  def show
  end

  def edit
  end

  def update
    if @train.update(train_params)
      redirect_to trains_path(@train)
    else
      render :edit
    end
  end


  def destroy
    @train.destroy
    redirect_to trains_path
  end

  private 

  def train_params
    params.require(:train).permit(:name, :source_station, :last_station, :start_time, :end_time)
  end

  def set_train
    @train = Train.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<div class="col-lg-12">
  <div class="card mt-5">
    <div class="card shadow-sm p-3 bg-white rounded">
      <div class="row">
        <h2 class="text-center" style="color: blue;">Search Train</h2>
        <div class="col-lg-12">
          <%= render "shared/search_form", q: @q, url: 'search_result' %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/home/search_result.html.erb
<div class="col-lg-12">
  <div class="card mt-5">
    <div class="card shadow-sm p-3 bg-white rounded">
      <div class="row">
        <h2 class="text-center" style="color: blue;">Search Train</h2>
        <div class="col-lg-12">
          <%= render "shared/search_form", q: @q, url: 'search_result' %>
        </div>
      </div>
    </div>
  </div>
  <% if @trains.present? %>
    <% @trains.each do |train| %>
      <div class="card mt-5 mb-5">
        <div class="card shadow-sm p-3 bg-white rounded">
          <p class="lead" style="font-size:30px"> 
            <%= link_to train.name, train, class: "link-primary" %>
          </p>
          <p class="font-weight-normal" style="color:black; font-size:20px; letter-spacing: 0.5px;">Starting From:<%= train.start_time.strftime("%H:%M %p") %></p>
          <p class="font-weight-normal" style="color:black; font-size:20px; letter-spacing: 0.5px;">To End:<%= train.end_time.strftime("%H:%M %p") %></p>
          <!-- button-view -->
          <%= link_to 'Read More', train, class: "btn btn-success btn-lg", style:"width: 150px;" %>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="card mt-5 mb-5">
      <div class="card-body">
        <p class="lead">Oops! No trains are available for particular Route.</p>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsListing</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
  <%= javascript_importmap_tags %>
</head>

<body>
  <%= render 'shared/header' %>
  <div class="container">
    <div class="row">
      <%= yield %>
    </div>
  </div> 
</body>
</html>

app/views/shared/_header.html.erb
<div class="col-lg-12">
  <nav class="navbar navbar-expand-lg navbar-light bg-info">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link active", area_current: "page" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>
</div>

app/views/shared/_search_form.html.erb
<%= search_form_for q, url: url do |form|  %>
  <div class="form-group mt-4">
    <%= form.label :source_station, "From:" %>
    <%= form.text_field :source_station_cont, class: "form-control", required: true %>
  </div>
  <div class="form-group mt-4">
    <%= form.label :last_station, "To:" %>
    <%= form.text_field :last_station_cont, class: "form-control", required: true %>
  </div>
  <div class="form-group mt-4 mb-3">
    <%= form.submit class: "btn btn-primary btn-lg" %>
  </div>
<% end %>

app/views/stations/_form.html.erb
<div class="col-lg-12">
  <%= form_with model: station, html: { data: { turbo: false } } do |form| %>

  <div class= "form-group mt-2">
    <%= form.label :code, "Code:", class: "col-md-4 control-label" %><br>
    <div class="col-lg-6">
      <%= form.text_field :code, class: "form-control" %>
      <% station.errors.full_messages_for(:code).each do |message| %>
      <p class="text-danger"><%= message %></p>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6">
      <div class= "form-group mt-2">
        <%= form.label :name, "Name:", class: "col-md-4 control-label" %><br>
        <div class="col-md-8">
          <%= form.text_field :name, class: "form-control" %>
          <% station.errors.full_messages_for(:name).each do |message| %>
          <p class="text-danger"><%= message %></p>
          <% end %>
        </div>
      </div>
    </div>
    

    <div class="col-lg-6">
      <div class= "form-group mt-2">
        <%= form.label :state, "State:", class: "col-md-4 control-label" %><br>
        <div class="col-md-8">
          <%= form.text_field :state, class: "form-control" %>
          <% station.errors.full_messages_for(:state).each do |message| %>
          <p class="text-danger"><%= message %></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col-lg-6">
      <div class= "form-group mt-2">
        <%= form.label :longitude, "Longitude:", class: "col-md-4 control-label" %><br>
        <div class="col-md-8">
          <%= form.number_field :longitude, class: "form-control" %>
          <% station.errors.full_messages_for(:longitude).each do |message| %>
          <p class="text-danger"><%= message %></p>
          <% end %>
        </div>
      </div>
    </div>


    <div class="col-lg-6">
      <div class= "form-group mt-2">
        <%= form.label :latitude, "Latitude:", class: "col-md-4 control-label" %><br>
        <div class="col-md-8">
          <%= form.number_field :latitude, class: "form-control" %>
          <% station.errors.full_messages_for(:latitude).each do |message| %>
          <p class="text-danger"><%= message %></p>
          <% end %>
        </div>
      </div>
    </div> 
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="form-group mt-3">
        <%= form.submit class: "btn btn-primary btn-lg rounded" %>
      </div>
    </div>
  </div>

  <% end %>
</div>

app/views/stations/edit.html.erb
<div class="col-lg-12">
  <div class="card rounded-0 mt-5 mb-5">
    <div class="card-body">
      <h2 class="text-center">Edit Station Detail</h2>
      <%= render "form", station: @station %>
    </div>
  </div>
</div>

app/views/stations/index.html.erb
<div class="col-lg-12">
  <%= link_to 'New Station', new_station_path, class: "btn btn-primary btn-lg rounded-0 mt-5" %>
  <h2 class="text-center">List of all Stations</h2>
  <table class= "table table-bordered mt-5">
    <thead>
      <tr>
        <th>Code</th>
        <th>Name</th>
        <th>State</th>
        <th>Longitude</th>
        <th>Latitude</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @stations.each do |station| %>
      <tr>
        <td><%= station.code %></td>
        <td><%= station.name %></td>
        <td><%= station.state %></td>
        <td><%= station.longitude %></td>
        <td><%= station.latitude %></td>
        <td><%= link_to 'View', station, class: "btn btn-success" %></td>
        <td><%= link_to 'Edit', edit_station_path(station), class:"btn btn-primary" %></td>
        <td><%= link_to 'Destroy', station, class: "btn btn-danger",method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/stations/new.html.erb
<div class="col-lg-12">
  <div class="card rounded-0 mt-5 mb-5">
    <div class="card-body">
      <h2 class="text-center">New Station</h2>
      <%= render "form", station: @station %>
    </div>
  </div>
</div>

app/views/stations/show.html.erb
<div class="col-lg-12">
  <div class="row">
    <div class="card mt-5">
      <div class="card-body">
       <div class="col-lg-12">
         <h5 class="text-center mt-2 mb-5" style="color:royalblue;">Code:<%= @station.code %></h5>
       </div>
       <div class="col-lg-6">
         <h5>Name:</h5>
         <p><%= @station.name %></p>
       </div>
       <div class="col-lg-6">
         <h5>State:</h5>
         <p><%= @station.state %></p>
       </div>
       <div class="col-lg-6">
         <h5>Longitude:</h5>
         <p><%= @station.longitude %></p>
       </div>
       <div class="col-lg-6">
         <h5>Latitude:</h5>
         <p><%= @station.latitude %></p>
       </div>
     </div>
     <!-- Association -->
    <table class= "table table-bordered mt-5">
      <thead>
        <tr>
          <th>Train Name</th>
          <th>Arrives</th>
          <th>Departs</th>
          <th>Halt Duration</th>
          <th>Days</th>
        </tr>
      </thead>
      <tbody>
       <% @station.train_stations.each do |station_train| %>
       <tr>
         <td><%= station_train.train.name %></td>
         <td><%= station_train.arrival_time.strftime("%H:%M %p")%></td>
         <td><%= station_train.departure_time.strftime("%H:%M %p") %></td>
         <td><%= station_train.total_halt_in_minutes.strftime("%H:%M:%S") %></td>
         <td><%= station_train.day %></td>
       </tr>
       <% end %>
     </tbody>
    </table>
 </div>
</div>
  <p class="mt-5">
   <%= link_to 'Back', stations_path, class: "btn btn-success btn-lg", style:"width: 90px;" %>
   <%= link_to 'Edit', edit_station_path(@station), class: "btn btn-primary btn-lg", style:"width: 90px;" %>
  </p>
</div>

app/views/train_stations/_form.html.erb
<div class="col-lg-12">
  <%= form_with model: train_station, html: { data: { turbo: false } } do |form| %>

  <div class= "form-group mt-2">
    <%= form.label :train_id, "Train:", class: "col-md-4 control-label" %><br>
    <div class="col-lg-6">
      <%= form.select :train_id, options_for_select(Train.pluck(:name, :id), selected: train_station.train_id), {prompt: 'Select Train'}, { class: 'form-select form-select-lg rounded-0'}%>
      <% train_station.errors.full_messages_for(:train_id).each do |message| %>
      <p class="text-danger"><%= message %></p>
      <% end %>
    </div>
  </div>

  <div class= "form-group mt-2">
    <%= form.label :station_id, "Station:", class: "col-md-4 control-label" %><br>
    <div class="col-lg-6">
      <%= form.select :station_id, options_for_select(Station.pluck(:name, :id), selected: train_station.station_id), {prompt: 'Select Station'}, { class: 'form-select form-select-lg rounded-0'}%>
      <% train_station.errors.full_messages_for(:station_id).each do |message| %>
      <p class="text-danger"><%= message %></p>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6">
      <div class= "form-group mt-2">
        <%= form.label :day, "Day:", class: "col-md-4 control-label" %><br>
        <div class="col-md-8">
          <%= form.number_field :day, class: "form-control" %>
          <% train_station.errors.full_messages_for(:day).each do |message| %>
          <p class="text-danger"><%= message %></p>
          <% end %>
        </div>
      </div>
    </div>
    

    <div class="col-lg-6">
      <div class= "form-group mt-2">
        <%= form.label :distance_in_km, "Distance(kms)", class: "col-md-4 control-label" %><br>
        <div class="col-md-8">
          <%= form.number_field :distance_in_km, class: "form-control" %>
          <% train_station.errors.full_messages_for(:distance_in_km).each do |message| %>
          <p class="text-danger"><%= message %></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col-lg-6">
      <div class= "form-group mt-2">
        <%= form.label :arrival_time, "Arrival Time:", class: "col-md-4 control-label" %><br>
        <div class="col-md-8">
          <%= form.time_field :arrival_time, class: "form-control" %>
          <% train_station.errors.full_messages_for(:arrival_time).each do |message| %>
          <p class="text-danger"><%= message %></p>
          <% end %>
        </div>
      </div>
    </div>


    <div class="col-lg-6">
      <div class= "form-group mt-2">
        <%= form.label :departure_time, "Departure:", class: "col-md-4 control-label" %><br>
        <div class="col-md-8">
          <%= form.time_field :departure_time, class: "form-control" %>
          <% train_station.errors.full_messages_for(:departure_time).each do |message| %>
          <p class="text-danger"><%= message %></p>
          <% end %>
        </div>
      </div>
    </div> 
  </div>


    <div class="col-lg-6">
      <div class= "form-group mt-2">
        <%= form.label :total_halt_in_minutes, "Halt:", class: "col-md-4 control-label" %><br>
        <div class="col-md-8">
          <%= form.time_field :total_halt_in_minutes, class: "form-control" %>
          <% train_station.errors.full_messages_for(:total_halt_in_minutes).each do |message| %>
          <p class="text-danger"><%= message %></p>
          <% end %>
        </div>
      </div>
    </div> 
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="form-group mt-3">
        <%= form.submit class: "btn btn-primary btn-lg rounded" %>
      </div>
    </div>
  </div>

  <% end %>
</div>

app/views/train_stations/edit.html.erb
<div class="col-lg-12">
  <div class="card rounded-0 mt-5 mb-5">
    <div class="card-body">
      <h2 class="text-center">Edit Detail</h2>
      <%= render "form", train_station: @train_station %>
    </div>
  </div>
</div>

app/views/train_stations/index.html.erb
<div class="col-lg-12">
  <%= link_to 'New Train_Station', new_train_station_path, class: "btn btn-primary btn-lg rounded-0 mt-5" %>
  <table class= "table table-bordered mt-5">
    <thead>
      <tr>
        <th>Train</th>
        <th>Station</th>
        <th>Day</th>
        <th>Distance(kms)</th>
        <th>Arrival Time</th>
        <th>Departure Time</th>
        <th>Halt(minutes)</th>
        <th colspan="2">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @train_stations.each do |train_station| %>
      <tr>
        <td><%= train_station.train.name %></td>
        <td><%= train_station.station.name %></td>
        <td><%= train_station.day %></td>
        <td><%= train_station.distance_in_km %></td>
        <td><%= train_station.arrival_time.strftime("%H:%M %p") %></td>
        <td><%= train_station.departure_time.strftime("%H:%M %p") %></td>
        <td><%= train_station.total_halt_in_minutes.strftime("%H:%M:%p") %></td>
        <td><%= link_to 'Edit', edit_train_station_path(train_station), class:"btn btn-primary" %></td>
        <td><%= link_to 'Destroy', train_station, class: "btn btn-danger",method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/train_stations/new.html.erb
<div class="col-lg-12">
  <div class="card rounded-0 mt-5 mb-5">
    <div class="card-body">
      <h2 class="text-center">New</h2>
      <%= render "form", train_station: @train_station %>
    </div>
  </div>
</div>

app/views/train_stations/show.html.erb
<div class="col-lg-12">
  <div class="row">
    <div class="card mt-5">
      <div class="card-body">
       <div class="col-lg-12">
         <h5 class="text-center mt-2 mb-5" style="color:royalblue;">Train_id:<%= @train_station.train_id %></h5>
         <h5 class="text-center mt-2 mb-5" style="color:royalblue;">Station_id:<%= @train_station.station_id %></h5>
       </div>
       <div class="col-lg-6">
         <h5>Day:</h5>
         <p><%= @train_station.day %></p>
       </div>
       <div class="col-lg-6">
         <h5>Distance:</h5>
         <p><%= @train_station.distance_in_km %></p>
       </div>
       <div class="col-lg-6">
         <h5>Arrival Time:</h5>
         <p><%= @train_station.arrival_time %></p>
       </div>
       <div class="col-lg-6">
         <h5>Departure Time:</h5>
         <p><%= @train_station.departure_time %></p>
       </div>

       <div class="col-lg-6">
         <h5>Total Halt:</h5>
         <p><%= @train_station.total_halt_in_minutes %></p>
       </div>
     </div>
     <!-- Association -->
    <table class= "table table-bordered mt-5">
      <thead>
        <tr>
          <th>Train Name</th>
          <th>Arrives</th>
          <th>Departs</th>
          <th>Halt Duration</th>
          <th>Days</th>
        </tr>
      </thead>
      <tbody>
       <% @station.train_stations.each do |station_train| %>
       <tr>
         <td><%= station_train.train.name %></td>
         <td><%= station_train.arrival_time.strftime("%H:%M %p")%></td>
         <td><%= station_train.departure_time.strftime("%H:%M %p") %></td>
         <td><%= station_train.total_halt_in_minutes.strftime("%H:%M:%S") %></td>
         <td><%= station_train.day %></td>
       </tr>
       <% end %>
     </tbody>
    </table>
 </div>
</div>
  <p class="mt-5">
   <%= link_to 'Back', stations_path, class: "btn btn-success btn-lg", style:"width: 90px;" %>
   <%= link_to 'Edit', edit_station_path(@station), class: "btn btn-primary btn-lg", style:"width: 90px;" %>
  </p>
</div>

app/views/trains/_form.html.erb
<div class="col-lg-12">
  <%= form_with model: train, html: { data: { turbo: false } } do |form| %>

  <div class= "form-group mt-2">
    <%= form.label :name, "Name:", class: "col-md-4 control-label" %><br>
    <div class="col-lg-6">
      <%= form.text_field :name, class: "form-control" %>
      <% train.errors.full_messages_for(:name).each do |message| %>
      <p class="text-danger"><%= message %></p>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-lg-6">
      <div class= "form-group mt-2">
        <%= form.label :source_station, "Source:", class: "col-md-4 control-label" %><br>
        <div class="col-md-8">
          <%= form.text_field :source_station, class: "form-control" %>
          <% train.errors.full_messages_for(:source_station).each do |message| %>
          <p class="text-danger"><%= message %></p>
          <% end %>
        </div>
      </div>
    </div>
    

    <div class="col-lg-6">
      <div class= "form-group mt-2">
        <%= form.label :last_station, "Destination:", class: "col-md-4 control-label" %><br>
        <div class="col-md-8">
          <%= form.text_field :last_station, class: "form-control" %>
          <% train.errors.full_messages_for(:last_station).each do |message| %>
          <p class="text-danger"><%= message %></p>
          <% end %>
        </div>
      </div>
    </div>
  </div>


  <div class="row">
    <div class="col-lg-6">
      <div class= "form-group mt-2">
        <%= form.label :start_time, "Starting from:", class: "col-md-4 control-label" %><br>
        <div class="col-md-8">
          <%= form.time_field :start_time, class: "form-control" %>
          <% train.errors.full_messages_for(:start_time).each do |message| %>
          <p class="text-danger"><%= message %></p>
          <% end %>
        </div>
      </div>
    </div>


    <div class="col-lg-6">
      <div class= "form-group mt-2">
        <%= form.label :end_time, "To End:", class: "col-md-4 control-label" %><br>
        <div class="col-md-8">
          <%= form.time_field :end_time, class: "form-control" %>
          <% train.errors.full_messages_for(:end_time).each do |message| %>
          <p class="text-danger"><%= message %></p>
          <% end %>
        </div>
      </div>
    </div> 
  </div>

  <div class="row">
    <div class="col-lg-12">
      <div class="form-group mt-3">
        <%= form.submit class: "btn btn-primary btn-lg rounded" %>
      </div>
    </div>
  </div>

  <% end %>
</div>

app/views/trains/edit.html.erb
<div class="col-lg-12">
  <div class="card rounded-0 mt-5 mb-5">
    <div class="card-body">
      <h2 class="text-center">Edit Train Detail</h2>
      <%= render "form", train: @train %>
    </div>
  </div>
</div>

app/views/trains/index.html.erb
<div class="col-lg-12">
  <%= render "shared/search_form", q: @q, url: :trains %>
  <%= link_to 'New Train', new_train_path, class: "btn btn-primary btn-lg rounded-0 mt-5" %>
  <h2 class="text-center">List of all Trains</h2>
  <table class= "table table-bordered mt-5">
    <thead>
      <tr>
        <th>Name</th>
        <th>Source Station</th>
        <th>Last Station</th>
        <th colspan="3">Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @trains.each do |train| %>
      <tr>
        <td><%= train.name %></td>
        <td><%= train.source_station %></td>
        <td><%= train.last_station %></td>
        <td><%= link_to 'View', train, class: "btn btn-success" %></td>
        <td><%= link_to 'Edit', edit_train_path(train), class:"btn btn-primary" %></td>
        <td><%= link_to 'Destroy', train, class: "btn btn-danger",method: :delete, data: {confirm: 'Are you sure?'} %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <%= paginate @trains %>
</div>

app/views/trains/new.html.erb
<div class="col-lg-12">
  <div class="card rounded-0 mt-5 mb-5">
    <div class="card-body">
      <h2 class="text-center">New Train</h2>
      <%= render "form", train: @train %>
    </div>
  </div>
</div>

app/views/trains/show.html.erb
<div class="col-lg-12">
  <div class="row">
    <div class="col-lg-12">
     <h5 class="text-center mt-2 mb-5" style="color:royalblue;">Name:<%= @train.name %></h5>
   </div>
   <div class="col-lg-6">
     <h5>Source Station:</h5>
     <p><%= @train.source_station %></p>
   </div>
   <div class="col-lg-6">
     <h5>Destination:</h5>
     <p><%= @train.last_station %></p>
   </div>
   <div class="col-lg-6">
     <h5>Starting From:</h5>
     <p><%= @train.start_time.strftime("%H:%M %p") %></p>
   </div>
   <div class="col-lg-6">
     <h5>To:</h5>
     <p><%= @train.end_time.strftime("%H:%M %p") %></p>
   </div>
   <div class="col-lg-6">
     <h5>Duration:</h5>
     <p><%= @train.train_duration %></p>
   </div>
 </div>
 <!-- associations -->
  <table class= "table table-bordered mt-5">
    <thead>
      <tr>
        <th>Halt Stations(Route)</th>
        <th>Days</th>
        <th>Distance</th>
        <th>Arrival Time</th>
        <th>Departure Time</th>
        <th>Halt Duration</th>
      </tr>
    </thead>
    <tbody>
      <% @train.train_stations.each do |train_station| %>
      <tr>
        <td><%= train_station.station.name %></td>
        <td><%= train_station.day %></td>
        <td><%= train_station.distance_in_km %></td>
        <td><%= train_station.arrival_time.strftime("%H:%M %p") %></td>
        <td><%= train_station.departure_time.strftime("%H:%M %p") %></td>
        <td><%= train_station.total_halt_in_minutes.strftime("%H:%M:%S") %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

<%= link_to 'Back', trains_path, class: "btn btn-success btn-lg" %>
<%= link_to 'Edit', edit_train_path(@train), class: "btn btn-primary btn-lg" %>
</div>